Sprint 2
KillReal63/yaburger pull request #6
Opened 2023-08-24 19:19 UTC by KillReal63

2023-08-24 19:44 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Dnd настроен и работает хорошо
- У табов подсвечивается ближайшая категория при скролле
- Правильно использовали redux-toolkit

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У слайса с заказом (order) так же необходимо описать все три состояния `pending `, `fulfilled ` и `rejected `
- У булок не отображается счетчик при добавлении в конструктор
- Необходимо отправлять на ендпоинт `/orders` массив с добавленными ингредиентами в конструктор. В ответе будет приходить номер заказа.
- Модальное окно с номером заказа не закрывается нажатием на подложку
- У `IngredientItem ` не хватает `propTypes`
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-24 19:44 UTC, andryxxa93 commented on src/Services/Slices/counter.js
> +    increment(state, action) {
**Можно лучше**
Подсчитывать количество ингредиентов отдельно в редьюсере - нет необходимости. Это желательно делать внутри списка ингредиентов.

2023-08-24 19:44 UTC, andryxxa93 commented on src/Components/Modal/Modal.jsx
> +  const { isOpen, open } = useSelector((store) => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-08-24 19:44 UTC, andryxxa93 commented on src/Components/BurgerIngredients/BurgerIngredients.jsx
> +      <Tabs activeTab={activeTab} />
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-08-25 14:48 UTC, andryxxa93 commented
**Необходимо исправить**
- Для получения номера заказа необходимо отправлять на ендпоинт `/orders` массив с добавленными ингредиентами в конструктор. В ответе будет приходить номер заказа.

2023-08-26 10:25 UTC, andryxxa93 requested changes
**Необходимо исправить**
- Вы отправляете не массив с айдишниками добавленных ингредиентов, а объект с булками и ингредиентами. Необходимо отсылать массив с айдишниками добавленных ингредиентов. Выглядеть это должно так:

```
// data = [''643d69a5c3f7b9001cfa093d, '643d69a5c3f7b9001cfa093d', ...]

    body: JSON.stringify({
      ingredients: data,
    }),
```

- Номер заказа необходимо доставать из ответа сервера, а не генерировать самостоятельно.

2023-08-26 11:18 UTC, KillReal63 commented
У меня приходит 404 тк бэка нет. И номер в ответ я получить не могу. В задании не было сказано про подготовку бэка

2023-08-27 09:53 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-27 10:45 UTC, merged