Sprint 3
KillReal63/yaburger pull request #7
Opened 2023-09-03 22:45 UTC by KillReal63

В целом почти всё сделал, сегодня днём-вечером догружу полностью. Осталось пофиксить пару багов. Прошу начать проверять работу

2023-09-04 01:50 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть автологин
- После регистрации юзер автоматически авторизуется
- Хорошая работа с запросами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Если в хранилище нет токенов то делать запрос данных юзера не нужно
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- Страница профиля не должна быть доступна если юзер не авторизован
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx .
- Роут `reset-password` должне быть доступен только из роута `forgot-password`
- В хедере следует использовать NavLink 
- Необходимо реализовать защиту роутов от авторизованных и не авторизованных юзеров
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Для этого используйте обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

- Не авторизованный юзер не должен иметь возможность сделать заказ
- Для записи куков следует использовать функцию из данной статьи - `https://learn.javascript.ru/cookie`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-04 01:50 UTC, andryxxa93 commented on src/Components/App/App.jsx
> +  const token = getCookie('accessToken');
**Можно лучше**
`accessToken ` и `refreshToken` часто встречаемые строки - их следует поместить в константы

2023-09-04 01:50 UTC, andryxxa93 commented on src/Components/App/App.jsx
> +          <Route path='/login' element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-09-05 06:09 UTC, andryxxa93 commented
**Необходимо исправить**
- При нажатии кнопки "Сохранить" - ничего не просходит.

<img width="439" alt="Снимок экрана 2023-09-05 в 09 06 39" src="https://github.com/KillReal63/yaburger/assets/60173362/dd392418-0703-4d4b-96a7-1e30d698e454">

- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx .

- Кнопки "Отмена" и "Сохранить" должны появляться при внесении изменений в инпуты на странице профиля. Кнопка "Сохранить" должна отправлять запрос на бек - пожалуйста обратите ещё раз внимание на чек-лист к проектной работе.

- Обновление токена должно работать так же и при изменении данных юзера

2023-09-08 11:03 UTC, KillReal63 commented
Только update пользователя корректно не работает, тк при отправтке PATCH запроса, он возвращает теже самые данные

2023-09-09 05:27 UTC, andryxxa93 commented
**Необходимо исправить**

- PATCH запрос уходит пустым, поэтому данные возвращаются те же
<img width="1034" alt="Снимок экрана 2023-09-09 в 08 24 56" 
src="https://github.com/KillReal63/yaburger/assets/60173362/d8f8d9fc-d520-4c99-9067-54e0f946124a">

2023-09-09 18:00 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-09 18:21 UTC, merged